exp_name: dp_custom

mdp:
  world: "custom" #"4x4", "20x20"
  N: 20
  start: [19, 0]
  goal: [[0, 19]]
  slip_prob: 0.0
  default_cost: 1.0
  rect_costs:
    - [16, 16, 19, 19, 0.1]   # cheap block
    - [5, 5, 14, 14, 10.0]    # expensive block
run:
  solver: "lp"   # dp | lp | both
lp:
  solver: "MOSEK"     # MOSEK | HIGHS | DEFAULT  