mdp:
  world: "4x4_pctl"   

run:
  solver: "pctl_lp"

lp:
  solver: "MOSEK"     # MOSEK | HIGHS | DEFAULT

pctl:
  p_goal_min: 1.0

  # Define named regions (flags)
  flags:
    - name: "G2"
      region:
        rect: [2, 0, 2, 1]     # row 2, cols 0..1
    - name: "G3"
      region:
        rect: [1, 0, 1, 1]     # row 1, cols 0..1
    - name: "G4"
      region:
        rect: [2, 1, 3, 3]     # rows 2..3, cols 1..3

  # Define Until specs by name
  until_specs:
    - name: "G2U_G3"
      A: "G2"
      B: "G3"

  # Region constraints
  region_constraints: 
  - type: "visit_region_max"
    region: "G4"
    p: 0.0


  # Until constraints
  until_constraints: 

  - type: "until_min"
    until: "G2U_G3"
    p: 0.7
